chore: refactor refresh methods
GoogleCloudPlatform/cloud-sql-python-connector pull request #294
Opened 2022-03-09 18:27 UTC by jackwotherspoon

Refactor refresh methods to match those of the [Cloud SQL Go Connector](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector).

Separate PR will make refresh methods into static methods within `refresh_utils.py`

2022-03-09 18:30 UTC, jackwotherspoon commented on tests/unit/test_instance_connection_manager.py
> +async def refresh(icm: InstanceConnectionManager, wait: bool = False) -> asyncio.Task:
Temporary solution: Will be removed with async interface PR when tests will run with same event loop as ICM and not need `run_coroutine_threadsafe`

2022-03-09 18:33 UTC, jackwotherspoon commented on tests/unit/test_instance_connection_manager.py
> +    return new_task
Temporary solution: Will be removed with async interface PR when tests will run with same event loop as ICM and not need `run_coroutine_threadsafe`

2022-03-09 18:38 UTC, jackwotherspoon commented on google/cloud/sql/connector/instance_connection_manager.py
> +            return await refresh_task
Is it okay to set `refresh_task` to current and next within here? Wonder if there is a way to not need the intermediary task of `refresh_task` and only deal with `scheduled_task`.

2022-03-10 20:30 UTC, kurtisvg requested changes

2022-03-10 20:30 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +                delay = await self.seconds_until_refresh()
Actually, I think would be better to move this calculation to happen as part of the perform refresh and make `delay` a required variable. There's really no reason to have `seconds_until_refresh` be a public interface for the ICM - we only use it in the one place, and I think it's more clear to explicitly pass in the value.

2022-03-10 20:30 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +                self._next = self._schedule_refresh()
I think we want this logic to be:

```python
if self._current is invalid: # expired
     # self._current is not useful anyway, so let's return the latest error
     self._current = refresh_task
# always schedule a new refresh if the last one was bad 
self._next = self._schedule_refresh(0)
```

2022-03-14 14:34 UTC, jackwotherspoon commented on google/cloud/sql/connector/instance_connection_manager.py
> +            self._next = self._schedule_refresh()
how come we want to set `self._next = self._current` here? Are we just trying to say let `schedule_refresh` deal with setting `self._next`? If that is the case we probably don't even need next to be set here.

2022-03-14 14:39 UTC, jackwotherspoon commented on google/cloud/sql/connector/instance_connection_manager.py
> +                delay = await self.seconds_until_refresh()
If we were to move `delay` into `perform_refresh` then how would `schedule_refresh` know how long to sleep for?

2022-03-14 14:59 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +            self._next = self._schedule_refresh()
I think you want to set `_next` here so that you can never have `self._next` be `None`.

2022-03-14 15:03 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +                delay = await self.seconds_until_refresh()
`schedule_refresh` takes delay as an argument (as opposed to optional). 

In `perform_refresh` where we call `schedule_refresh`, we pass in delay (as opposed to using the "default"). `perform_refresh` can do the calculation for delay in the function, as opposed to relying on `seconds_until_refresh`.

2022-03-15 22:28 UTC, kurtisvg requested changes

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
>              return False
This section is feeling a bit wonky. Where do we expect an `Exception` to be thrown? Is it just `cancel()`? If so I think we should move L327-L329 out of the try/catch. I don't think we want to return false if we actually scheduled a refresh (but I don't think we can get an error there anymore)

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +        # if a new refresh is already in progress, then block on the result
```suggestion
        # if a new refresh is already in progress, then block new connections on the next result
```

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +    def _schedule_refresh(self, delay: int) -> asyncio.Task:
nit: should this be `asyncio.Task[InstanceMetadata]`?

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +                delay = await self._seconds_until_refresh()
Can we make `_seconds_until_refresh` either something on InstanceMetadata or a standalone function? I don't think it needs access to `self` here.

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +                        )
I feel like this bit is making the rest hard to read. What do you think about an `is_valid` function to help here:

```python
def is_valid(task: asyncio.Task[InstanceMetadata]) -> bool:
     try: 
          md = await task
         # only valid if now is before the cert expires
          if datetime.datetime.now() < instance_data.expiration:
              return True
      except Exception:
           # surpress any errors from task
      return False
```

Should help simplify this try/catch nest quite a bit

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +                delay = await self._seconds_until_refresh()
I'm also not sure we need another context switch here - we should have the result of `instance_data` from the await of `refresh_task` earlier, which should be what we need to calculate the delay

2022-03-15 22:28 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +            return await refresh_task
We're already awaiting this on L458, we should save that value and return it here (rather than an extra context switch)

2022-03-16 18:19 UTC, kurtisvg approved these changes

2022-03-16 20:20 UTC, merged

2022-03-17 20:13 UTC, jackwotherspoon commented
Closes #103