chore: refactor connect into connect_info
GoogleCloudPlatform/cloud-sql-python-connector pull request #304
Opened 2022-03-22 18:23 UTC by jackwotherspoon

Closes #290

2022-03-22 20:14 UTC, kurtisvg requested changes

2022-03-22 20:14 UTC, kurtisvg commented on google/cloud/sql/connector/instance_connection_manager.py
> +        return (instance_data, ip_address)
nit: You don't need to explicitly bundle this in a tuple, python does it automatically with just `return a, b`

2022-03-22 20:14 UTC, kurtisvg commented on google/cloud/sql/connector/utils.py
> +def clean_input(default_ip_type: Any, default_timeout: int, **kwargs: Any) -> Any:
We're only using this in the 1 place - is it really worth separating out into it's own function?

2022-03-22 20:14 UTC, kurtisvg commented on google/cloud/sql/connector/connector.py
> +    )
nit: these 3 functions might be easier to find if we move the into their own files

2022-03-22 20:14 UTC, kurtisvg commented on google/cloud/sql/connector/connector.py
> +) -> Any:
I don't really understand this function's signature (or why we need it). It's also very short (minus the docstring). Are we sure we shouldn't inline here?

2022-03-29 16:04 UTC, kurtisvg requested changes

2022-03-29 16:04 UTC, kurtisvg commented on google/cloud/sql/connector/utils.py
> +logger = logging.getLogger(name=__name__)
Are we using these here?

2022-03-30 16:18 UTC, jackwotherspoon commented on google/cloud/sql/connector/connector.py
> +            **kwargs: Any,
Removed need for these arguments.

2022-03-30 22:18 UTC, kurtisvg approved these changes

2022-03-30 22:18 UTC, kurtisvg commented on google/cloud/sql/connector/connector.py
> +
nit: 
```suggestion
```

2022-04-01 18:19 UTC, merged